### ISSUE TITLE
Connection refused, CORS error

### ISSUE THREAD

**Issue by gravitymedianet** [apenab/react-dymo-hooks#3]
Hello, I came across your solution as I need to print dymo labels from my app.

When I implemented your sample code, I keep getting Connection Refused error from Chrome. It seems like a CORS issue.

Do you know what steps need to be take to resolve this?

**Comment by gravitymedianet** [comment]
UPDATE:

I used your sample code in the examples folder and that worked. Not sure why the sample code on your documentation doesn't work. But the other did! Thanks!

**Comment by apenab** [comment]
What version of Dymo Label Service are you using?

**Comment by apenab** [comment]
I just tried with the `DLS8Setup8.7.exe` and work properly
